\encoding UTF8
---------------------------- ESERCIZO 11 ----------------------------
SELECT DISTINCT CS.NOME
FROM CORSOSTUDI CS

EXCEPT

SELECT DISTINCT CS.NOME
FROM CORSOSTUDI CS
	JOIN INSEROGATO IE ON IE.ID_CORSOSTUDI = CS.ID
    JOIN INSEGN I ON I.ID = IE.ID_INSEGN
WHERE I.NOMEINS ILIKE '%MATEMATICA%'