\encoding UTF8
---------------------------- ESERCIZO 6 ----------------------------
SELECT CS.NOME, COUNT(IE.ID)
FROM CORSOSTUDI CS
	JOIN INSEROGATO IE ON IE.ID_CORSOSTUDI = CS.ID
    JOIN FACOLTA F ON F.ID = IE.ID_FACOLTA
WHERE IE.ANNOACCADEMICO = '2010/2011' AND
	IE.HAMODULI > '0' AND
	UPPER(F.NOME) <> 'MEDICINA E CHIRURGIA'
GROUP BY CS.NOME;