\encoding UTF8
---------------------------- ESERCIZO 5 ----------------------------
SELECT F.NOME, COUNT(IE.ID), SUM(IE.CREDITI)
FROM FACOLTA F
	JOIN INSEROGATO IE ON IE.ID_FACOLTA = F.ID
WHERE IE.MODULO < 0 AND
	IE.ANNOACCADEMICO = '2010/2011'
GROUP BY F.NOME