\encoding UTF8
---------------------------- ESERCIZO 9 ----------------------------
SELECT DISTINCT I.NOMEINS, IE.DISCRIMINANTEMODULO
FROM INSEGN I
	JOIN INSEROGATO IE ON IE.ID_INSEGN = I.ID
    JOIN CORSOSTUDI CS ON CS.ID = IE.ID_CORSOSTUDI
    JOIN DOCENZA D ON D.ID_INSEROGATO = IE.ID
    JOIN PERSONA P ON P.ID = D.ID_PERSONA
WHERE CS.ID = 240 AND
	IE.MODULO = 0 AND
	UPPER(P.NOME) NOT IN('ROBERTO', 'ALBERTO', 'MASSIMO', 'LUCA') AND
	IE.ANNOACCADEMICO = '2009/2010'
    
INTERSECT 
    
SELECT DISTINCT I2.NOMEINS, IE2.DISCRIMINANTEMODULO
FROM INSEGN I2
	JOIN INSEROGATO IE2 ON IE2.ID_INSEGN = I2.ID
    JOIN CORSOSTUDI CS2 ON CS2.ID = IE2.ID_CORSOSTUDI
    JOIN DOCENZA D2 ON D2.ID_INSEROGATO = IE2.ID
    JOIN PERSONA P2 ON P2.ID = D2.ID_PERSONA
WHERE CS2.ID = 240 AND
	IE2.MODULO = 0 AND
	UPPER(P2.NOME) NOT IN('ROBERTO', 'ALBERTO', 'MASSIMO', 'LUCA') AND
	IE2.ANNOACCADEMICO = '2010/2011'
 ORDER BY 1
