\encoding UTF8
---------------------------- ESERCIZO 13 ----------------------------
SELECT SS.NOMESTRUTTURA, SS.FAX, COUNT(CS.ID)
FROM CORSOSTUDI CS
	JOIN STRUTTURASERVIZIO SS ON SS.ID = CS.ID_SEGRETERIA
GROUP BY SS.NOMESTRUTTURA, SS.FAX